server:
  port: 8080

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

app:
  jwt:
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
